### ISSUE TITLE
Does it supports mathematical equations ?

### ISSUE THREAD

**Issue by gulabsagevadiya** [krishnachaitanya0107/TextRecognizerApp#1]
I just want to know if this ml kit does support mathematical equations to latex conversation ?

**Comment by krishnachaitanya0107** [comment]
Hi @gulabsagevadiya ,
As far as i know , The ML kit does not support mathematical equations to latex conversation right now .

**Comment by gulabsagevadiya** [comment]
Is there any free solution for image to latex like mathpix ? For simpler math equations? Specifically for android

**Comment by krishnachaitanya0107** [comment]
Well Unfortunately I couldn't find any free solution for image to latex for android . But since it is about simpler math equations , One temporary solution could be to use text recognition in ML kit to extract text from an image and then maybe convert that extracted string into latex , Although This isn't the best solution because most of the time the text recognition seems to fail in recognizing math symbols which could be problematic .

**Comment by AndroidDeveloperLB** [comment]
Is it possible to somehow make it learn non-English letters too?
How do you teach it to learn other languages?

**Comment by krishnachaitanya0107** [comment]
@AndroidDeveloperLB  the official documentation says that this ML kit can recognise text across latin-based languages . Here is a link to the documentation -  https://developers.google.com/ml-kit/vision/text-recognition 

But if you want to teach it some other language . You can train your own model by providing some sample data here - 
 https://teachablemachine.withgoogle.com/ 
 
And then use the generated ML model in your android app .

**Comment by AndroidDeveloperLB** [comment]
@krishnachaitanya0107 Oh sorry for this. Still I was talking about something similar.
Is it a hard thing to teach and use it?
I've noticed that even on the sample, it often fails to recognize English letters well. 
Did you teach it, or was it Google?

**Comment by gulabsagevadiya** [comment]
Hey I have one question about this technology.
I already have so many LaTeX code. And I can generate their mathematical equations images with some android library. 
So can I train model to convert image to LaTeX code with teachablemachine?

**Comment by krishnachaitanya0107** [comment]
@AndroidDeveloperLB in the sample i actually used a pre-trained model by Google , and yeah it fails to recognise text properly sometimes. I brought up the teachable machine part only because you wanted a way to recognise non English letters. 

The teachable machine by Google isn't actually hard to use , you just need to have enough training data to train the model . The more the data you provide it , the more accurate the model will be .

**Comment by krishnachaitanya0107** [comment]
@gulabsagevadiya  If you have data to train the model , then you can go ahead and give it a try .
